# Generated by Django 4.0.3 on 2022-10-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Crypta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст Новости')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата опубликования')),
            ],
            options={
                'verbose_name': 'КриптоНовость',
                'verbose_name_plural': 'КриптоНовости',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст Новости')),
                ('chance', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Нейронка')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата опубликования')),
                ('category_news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='new.category_news', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
