# Generated by Django 4.0.3 on 2022-10-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='img_news',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
